// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAEBQSu-RtoagMc93UX-iRpvCSA3oRBBAU',
//     appId: '1:969115589653:web:bdc0c085a2a8039618c21c',
//     messagingSenderId: '969115589653',
//     projectId: 'cocory-1floor-kiosk',
//     authDomain: 'cocory-1floor-kiosk.firebaseapp.com',
//     databaseURL: 'https://cocory-1floor-kiosk-default-rtdb.firebaseio.com',
//     storageBucket: 'cocory-1floor-kiosk.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCny4E18z3_YzQmDv5jRqYrKF0mh3dac6k',
//     appId: '1:969115589653:android:4d08207010d71f9c18c21c',
//     messagingSenderId: '969115589653',
//     projectId: 'cocory-1floor-kiosk',
//     databaseURL: 'https://cocory-1floor-kiosk-default-rtdb.firebaseio.com',
//     storageBucket: 'cocory-1floor-kiosk.appspot.com',
//   );
//
// }